name 'yum-chef'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'apache 2.0'
description 'Configures yum repository for Chef Software, Inc. products'
version '0.1.0'
depends 'yum'
